### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#20]
Add authentication - should cover:
- [x] local, offline development (#35)
- [x] enabling identity in module projects (e.g. Leaderboard) (#37)
- [x] work out how authn/z works for gamer vs publisher (#38)
- [x] Support first sign-in flow, i.e. no gamer tag yet
- [x] Support subsequent sign-in, and set gamer tag in claims
- [ ] Enable non-temp certs (#257)
- [x] Enable persistent user store  (#169)
- [ ] Enable persistent user grant store (#230)
- [x] Enable interactive flow (#259)
- [ ] Self sign-up with username and password? (#258)
- [ ] Azure AD B2C (#36)
- [ ] understand how authn works from Xamarin (#40)
- [ ] understand how authn works from Unity (#41)
