### ISSUE TITLE
Enable guest logins

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#430]
Currently, Nether requires a logged in user to post scores, save player state, or send user game events. To enable a broader reach, we will enable this functionality to be used with a guest login. Guest logins will be transparent to the user and create an underlying user not associated with a login provider (e.g. facebook, username+password)

Steps:
 - [x] #431 - Change nether blocks to use userid as Primary Key instead of gamertag
 - [x] #432 - Add ability to log in as guest
 - [x] #433 - Add ability to convert guest user to authenticated user
 - [x] Update docs (each step should update the relevant docs, but we should do another check!)

**Comment by ankodu** [comment]
Looks good to me @stuartleeks . No specific feedback.

**Comment by stuartleeks** [comment]
@oliviak, @krist00fer - once we make the shift to guest logins we will have players without a gamertag set. Does the analytics pipeline handle that currently?
