### ISSUE TITLE
Steps to make it easier to broaden involvement

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#85]
We've talked a few times about what we need to get in place before opening this up to broader involvement, so I've created this issue to discuss/track what those pieces of work are :-)

This is just a starting point for discussion ;-)
- [x] Instructions on how to clone, build and run the solution #99
- [x] Guidelines on contributing #100
- [ ] Define the MVP #98 
- [ ] More complete API design to enable people to pick up a piece of a service and get started implementing (focus on the MVP)
- [ ] Authentication - start with facebook auth #41 
- [ ] deployment?
- [x] Integration tests for the existing code

Agree/disagree?...
